### PR TITLE
[Add profile] -> [Melford Birakor]

### PR DESCRIPTION
**Pull request by Melford-D**
### What does this PR do?:
Add my profile to the contributor's list

### CODE REVIEW

**Comment by Melford-D** [comment]
I have created a PR to add my profile. Kindly check it out.
Thank you.

**Review by Evavic44 — APPROVED** [review]
Awesome work Melford! Thanks for your contribution. 🤩🙌🏾

**Comment by Melford-D** [comment]
My pleasure

**Comment by Melford-D** [comment]
> Awesome work Melford! Thanks for your contribution. 🤩🙌🏾

We move!

**Pull request merged**
